fix: update check failing with TypeError (#5877)
since 22.11.1 the update check was failing with
TypeError: update_notifier_1.default is not a function